apiVersion: v1
kind: Namespace
metadata:
  name:  ns1

---
#service to be consumed

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: ns1
spec:
  replicas: 2
  selector:
    matchLabels:
      role: nginx1
  template:
    metadata:
      labels:
        role: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx
---
kind: Service
apiVersion: v1
metadata:
  name:  nginx1
  namespace: ns1
spec:
  selector:
    role: nginx1
  type: NodePort
  ports:
  - port:  80
    targetPort:  80

---
#service consumer of local svc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1-consumer
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      role: ns1-consumer
  template:
    metadata:
      labels:
        role: ns1-consumer
    spec:
      containers:
      - name: svc1-consumer
        image: ubuntu
        command:
          - /bin/sh
        args: 
          - "-c"
          - "apt update; apt install curl -y; while true; do curl -I nginx1; sleep 1;done"