apiVersion: v1
kind: Namespace
metadata:
  name:  ns2

---
#service to be consumed

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: ns2
spec:
  replicas: 2
  selector:
    matchLabels:
      role: nginx2
  template:
    metadata:
      labels:
        role: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx
---
kind: Service
apiVersion: v1
metadata:
  name:  nginx2
  namespace: ns2
spec:
  selector:
    role: nginx2
  type: NodePort
  ports:
  - port:  80
    targetPort:  80

---
#service consumer

#service consumer of local svc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2-consumer
  namespace: ns2
spec:
  replicas: 1
  selector:
    matchLabels:
      role: ns2-consumer
  template:
    metadata:
      labels:
        role: ns2-consumer
    spec:
      containers:
      - name: svc2-consumer
        image: ubuntu
        command:
          - /bin/sh
        args: 
          - "-c"
          - "apt update; apt install curl -y; while true; do curl -I nginx2; sleep 1;done"